@host = http://localhost:5000/api
@categoryPath = /categories
@categoryId = /dskljfklsdjf

### 
# get all users
GET http://localhost:5000/api/categories

###
# get category by id
GET {{host}}{{categoryPath}}{{categoryId}}

###
# save category 
POST {{host}}{{categoryPath}}
Content-Type: application/json

{
    "name": "category 3",
    "description": "cat 3",
    "createdBy": "68da0fdd4b407391328928a5"
}